### ISSUE TITLE
chore: cleanup eslint rules

### ISSUE THREAD

**Issue by hoebbelsB** [rx-angular/rx-angular#1548]
# Description

We have plenty of eslint activated that make no sense for our library and get disabled manually all over the place.

* @angular-eslint/directive-selector
* @angular-eslint/directive-class-suffix
* @angular-eslint/component-selector
* @angular-eslint/component-class-suffix
* @angular-eslint/no-input-rename
* @typescript-eslint/member-ordering
* @typescript-eslint/no-non-null-assertion -> I would rather suggest finally going for strict mode

On the other side we are missing some very useful eslint rules:

* [simple-import-sort](https://www.npmjs.com/package/eslint-plugin-simple-import-sort)/imports
* [simple-import-sort](https://www.npmjs.com/package/eslint-plugin-simple-import-sort)/exports
* [unused-imports](https://www.npmjs.com/package/eslint-plugin-unused-imports)

# Tasks

* [ ] clean up eslint rules and unify them. This may also affect the imported plugins
* [ ] remove `// eslint-disable-next-line` comments where possible
* [ ] add new rules as suggested
* [ ] run `eslint --fix` for all files

**Comment by Naaajii** [comment]
I would like to work on this but I cant even get the project to run:

![image](https://user-images.githubusercontent.com/54370141/235364988-99eb815d-4619-439e-a0e4-bd669093556a.png)

nor I cant run the script from package.json for linting:

![image](https://user-images.githubusercontent.com/54370141/235365038-13391805-9771-4447-97cb-41e6d6f9877e.png)

beginner to open source and nx here, I would appreciate the tips to learning my mistakes!

**Comment by hoebbelsB** [comment]
hi @Naaajii thanks for helping us out :)

> I would like to work on this but I cant even get the project to run:

That's not really your fault, the configuration of the demos app is weird. The app is running, you just need to navigate to the correct path: `http://localhost:4300/rx-angular/demos`. The empty path just returns an error...


> nor I cant run the script from package.json for linting:
> 
> beginner to open source and nx here, I would appreciate the tips to learning my mistakes!

No worries, here are some example commands to run the linter for projects

```bash
# lint a single project
nx run projectName:lint
# e.g.
nx run template:lint

# lint all projects
nx run-many --target=lint

# lint some projects
nx run-many --target=lint --projects=cdk,template,state
```

**Comment by Naaajii** [comment]
I have added new rules to the workspace repo, please correct me if I have done anything wrong.

I need some heads up I did some logs reading from linting output. I need some directions.

should spec files be included in `ignorePatterns`?
what should we do with following warnings as they are all over the place:

- `Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any`
- `Empty block statement                     no-empty`
- `'intersectionObserver' is defined but never used  @typescript-eslint/no-unused-vars`

remove them? disable them ( tho doing that would be same as doing what we are supposed to in this issue )?  fix them one-by-one? I'm sure we can't just fix them by passing --fix as we can for unused imports or sorted imports/exports.

additionally - [eslint-plugin-unused-imports](https://github.com/sweepline/eslint-plugin-unused-imports) comes with no-unused-vars which is same as [@typescript-eslint/no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars). I am unsure what to keep.

**Comment by hoebbelsB** [comment]
let's move the discussion to the PR :)
