### ISSUE TITLE
rxFor 

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#304]
# rxFor

Current implementation available here (rxFor)[https://github.com/rx-angular/rx-angular/tree/master/apps/demos/src/app/rx-angular-pocs/template/directives/for] until released under `rx-angular/template`

Demo:
1. `git clone git@github.com:rx-angular/rx-angular.git`
2. `cd rx-angular`
2. yarn 
3. nx s
4. http://localhost:4200/rx-angular/demos/

## Case Study
The subject is a nested DOM structure rendered as a table with 10 rows and 5 columns every column contains 1 template expression.
The template structure is built with 2 nested `ngFor` directives.

**The situation explained in steps:**
- A list is initially rendered
- The list is updated 4 times in a row with breaks
- The list is updated as fast as possible for some seconds on a `setInterval`
- A list is destroyed

__`ngFor` - Initialize; 4 updates by button; some seconds; as fast as possible, destroy__
<img width="959" alt="ng-for-init-5-click -interval" src="https://user-images.githubusercontent.com/10064416/103499000-e74a1000-4e46-11eb-8d7e-a93e96fecade.PNG">

# Prior Ar

`*ngFor="let item of array"`

Local Variables:
- index
- first
- even
- odd
- last

```html
<div *ngFor="let item of array; trackBy: trackById">
  <div *ngFor="let child of item.children; trackBy: trackById">
   {{child}}
  </div>
</div>
```

# Problem Solved By The Feature

There are several key factors that have a negative impact on rendering performance. The most common of them are rendering big lists of data - or in other terms: lots of workloads.
For rendering lists of data as templates, we typically use the `ngFor` Directive.
Its implementation is pull-based and relies on the current rendering mechanism of dirty marking and top-down (depth-first) evaluation triggered by zone.js, thus only being able to render all changes **synchronously**.

## Bootstrapping

Render a number of items that happen synchronously. This means all items are created in the same browser tick.
<img width="828" alt="sync-rendering-of-items" src="https://user-images.githubusercontent.com/10064416/96523165-52873b80-1275-11eb-8cc9-5385d4544adf.PNG">

This is very good for small to mid-size lists or small lists with a lot of DOM structure. 
For larger lists, this results in blocking UI. 

## Process change detection and render work in chunks

`ngFor` is not able to execute its work in batches. This relates to blocking UI when `create`, `update`, and `destroy` items. 

```html
<ul>
    <ng-container>
        <li *ngFor="let itme of array">{{item}}</li>
   </ng-container>
</ul>

<p>High priority content hidden until the list is rendered</p>
```
![Untitled presentation (5)](https://user-images.githubusercontent.com/10064416/103491476-7e51a080-4e24-11eb-82ff-514b9827b90a.png)

## Laziness of DOM (Template creation)

`ngFor` is not able to render lazily. To display some loading skeleton we have to wrap it in a `ngIf` to provide that. 

```html
<ng-template #loadingView>
    <li>Loading...</li>
</ng-template>

<ul>
    <ng-container *ngIf="array?.length; else loadingView">
        <li *ngFor="let itme of array">{{item}}</li>
   </ng-container>
</ul>
```

## Template Management

Consider something like an "admin interface" with lots of different widgets, tables and complex controls.
Users will eventually display and hide parts of the UI. This can be in a low frequency when e.g. hiding showing menu items, or in a high frequency when they sort, filter, move items in the different UI controls and tables. 

Those situations suffer again from if the process of rendering will take place synchronously.
 
## Nested Structures

Due to the top-down dirty checking mechanism especially the nested structures suffer from it. Here we have to evaluate the full data structure to detect a change. 

## Destruction

It takes a significant amount of time longer to destroy the component list than creating it.
<img width="506" alt="add-and-remove" src="https://user-images.githubusercontent.com/10064416/96657569-d2c7a280-1342-11eb-80aa-793488c66ec4.PNG">

## Render/Update Notifications

ATM the rendering (and removing) happens sync, but even here we run into situations where we need to get e.g. the actual dimensions for the list to position it. `ngFor` and all other structural directives do not provide such notifications

# Solution

`rxFor` targets this need. 

```html
<div *rxFor="let item of array$; trackBy: trackById; let children$ = select(['children'])">
  <div *rxFor="let child of children$; trackBy: trackById">
   {{child}}
  </div>
</div>
```

I'll first list the techniques/existing tools we could integrate and later the features.

__`rxFor` - Initialize; 5 updates by button; some seconds; as fast as possible__
<img width="960" alt="rx-for-init-5-click -interval" src="https://user-images.githubusercontent.com/10064416/104115175-88840b00-530c-11eb-8d5b-35025b3b0e07.PNG">

![chunk](https://user-images.githubusercontent.com/4904455/103594783-f1791680-4ef9-11eb-9f1e-b4fd4bc8b3dc.gif)

## Concepts:

- [x] Push based architecture
- [x] Immutable as well as mutable data structures (with `distinctBy`)
- [x] Reactive as well as imperative values in the template (ngFor drop-in replacement)
- [x] 💡`ListManager`: special logic for differ mechanism to avoid overrendering; abstracts away low level logic
- [x] render every `EmbeddedView` on its own while applying the configured `StrategyCredentials#behavior`
- [x] detach `EmbeddedView` to avoid `ChangeDetection` top-down rendering interference when scheduling
- [x] 💡cancel any scheduled work if a `remove` was triggered for an `index`
- [x] 💡cancel an `update` if a new `update` was triggered for the same `index`

> **💡 Pro Tip: Use different strategies for best UX**
> Based on the outcome of your processed items you can prioritize that work over strategies, 
> and get important things rendered immediately e.g. tool-tips and unimportant dom structure later e.g. things outside the view port.

## Features:

**Change propagation:**
- [x] When an item is added, a new instance of the template is added to the DOM [insert].
- [x] When an item is removed, its template instance is removed from the DOM [remove].
- [x] When items are updated, their respective templates are updated in the DOM [update].
- [x] When items are reordered, their respective templates are reordered in the DOM [move].
- [x] If [update] happens, only the respective `EmbeddedView` updates its context values, 
   and CD is called on it to update any template expression `{{}}`, `<div [ngClass]="{...}">`.
- [x] If [move], [remove] or [insert] happens, all `EmbeddedView` update thier context values,
  and CD is called on all of them to update any template expression `{{}}`, `<div [ngClass]="{...}">`.
- [x] If [insert] or [remove] happens, the parent will get CDed as well to update any
   `ViewQuery` like `@ViewChild`, `@ViewChildren`, `@ContentChild`, `@ContentChildren`.
- [x] After an item got inserted, its `EmbeddedView` gets detached from change detection and only re-atached before the `ListManager` calls CD the `EmbeddedView`. 

> **💡 Pro Tip:  Keep your mental model** 
> As Embedded Views are detached, we can think about `rxFor`'s as components. Every value that is inside it needs to be  
> included in its property bindings. In our case the binding of the directive.

**Local variables:**
- [x] $implicit: `T`
- [x] item$: `Observable<T>` 
- [x] index: `number`
- [x] count: `number`
- [x] first: `boolean`
- [x] last: `boolean`
- [x] even: `boolean`
- [x] odd: `boolean`
- [x] index$: `Observable<number>`
- [x] count$: `Observable<number>`
- [x] first$: `Observable<boolean>`
- [x] last$: `Observable<boolean>`
- [x] even$: `Observable<boolean>`
- [x] odd$: `Observable<boolean>`
- [x] 💡 select: `(keys: string[], distinctByMap): Observable<Partial<T>> (reactivity in the embedded view)`

> **💡 Pro Tip: Use `select` in nested structures to maintain render performance**
>  As the variables bound to the template is static, we lose control over rendering. 
> Here `select` can be used to derive properties of the items as observable.

**Properties:**
- [x] trackBy: `(index: number, item: T) => any`
- [x] 💡 trackBy: `string`
- [x] 💡 distinctBy: `(item: T, item: T) => boolean`
- [x] distinctBy: `string`
- [x] 💡 strategy: `string | Observable<string>`

> **💡 Pro Tip: Use property names directly as `trackBy` value**
> As functions can't get declared in the template we have to create `the `trackBy` functions always in the component, and add more nice to the codebase.
> With `rxFor` we can specify the property used to track the items directly in the template.~~

# Challenges 

- [x] When a new template is inserted, or an already existing template is removed from the `ViewContainerRef`,
  all components which have a  `ViewQuery` needs to get updates (???):
     - [x] `@ViewChild`
     - [x] `@ViewChildren`
     - [x] `@ContentChild`
     - [x] `@ContentChildren`
     
If `content-child` adds or removes from its ViewContainerRef `view-child` needs a change-detection
```html
<view-child>
  <content-child *rxLet="trigger$;let value">
    {{value}}
  </content-child>
</view-child>
```
- [x] When a template is rerendered we need to call `detectChanges` on the host
- [x] Loading Spinner (`rxContext`) #450 
- [x] Faster diffing and integration of strategies #451 
- [x] When projected in a component with OnPush we need to detect that component too. https://github.com/angular/angular/pull/35428
- [x] strategy mixing
- [x] cancelable updates
- [x] Error handling (should end up in a similar render result as e.g. `*ngFor` )

![image](https://user-images.githubusercontent.com/4904455/114473884-60e75c00-9bf5-11eb-971c-fa5dc3c11a24.png)

- [x] Third party compatibility 
  - Material CDK

# Todos
- [x] Marble tests!!!

# Alternatives Considered

- Split up the array outside of the template and feed the template in chunks of items

# Comparison
<img width="952" alt="ng-for-vs-rx-for" src="https://user-images.githubusercontent.com/10064416/104115154-54a8e580-530c-11eb-9f98-36984011ec90.PNG">

![ngFor](https://user-images.githubusercontent.com/10064416/105634718-d0a04300-5e5f-11eb-9f49-00d34fb283a4.PNG)
![rxFor](https://user-images.githubusercontent.com/10064416/105634722-d433ca00-5e5f-11eb-9e22-8d1f5854a2a4.PNG)

# Real live use case in large scale app

The shown measurement compares a fully frozen UI built with `ngFor` compared with the same code using `rxFor`.
Even if it takes way longer to display all elements users gave overall feedback that is incredible faster.

This first seems a paradox, but as the UI is non-blocking the user can interact with the page, get hover highlights, and can even navigate away while the list is expanding (remaining render work is canceled).
Due to this reason environment, it is an overall improvement for the user.

Note: In this example, we had to switch `patchZone` on to get click interaction based on global change detection working.
In a second improvement step, the clicks can trigger a `Subject` and the rendering would speed up even more as only new items get change detected.

![real-live_usecase](https://user-images.githubusercontent.com/10064416/109371250-5fabdb00-78a4-11eb-9b2a-d210df0a1491.png)

# Additional Context

- https://github.com/angular/angular/issues/37285
- https://github.com/angular/angular/issues/36878
- https://github.com/angular/angular/issues/19098
- Can we solve the sequential rendering of items in the list (promise, request animation frame, etc)?
- Working with objects

**Comment by BioPhoton** [comment]
@hoebbelsB @Karnaukhov-kh @kajetansw 
Please feel free to directly edit the comment and add additional information.

**Comment by Karnaukhov-kh** [comment]
Can we solve the sequential rendering of items in the list (promise, request animation frame etc)?

**Comment by Karnaukhov-kh** [comment]
Working with objects

**Comment by vmasek** [comment]
@BioPhoton is this planning to focus only on the empty state (`array?.length`) or should it also somehow support the loading/loaded state?

To explain the loading state:
In our apps, we usually use the entity pattern with a `loading` or even `loaded` flag beside the data itself. 

This means we have 4 states for the UI
A. Loading spinner
B. Loaded & displayed data
C. Loading new data (& displaying the old data underneath the loading overlay)
D. No data loaded (Resource is empty and thus a nice infographic can be shown)

**Comment by BioPhoton** [comment]
We could try to mingle out suspense control in issue #394 or even better create a rfc issue for the suspense handling, as it will be the same across all directives

**Comment by volser** [comment]
did you test how it will work with cdk drag and drop?
https://material.angular.io/cdk/drag-drop/overview

**Comment by BioPhoton** [comment]
@volser added it to the todos.
Feel free to suggest more edge cases :)

**Comment by BioPhoton** [comment]
As it is in master lets close this one :)

**Comment by exequiel09** [comment]
@BioPhoton how do we start using `rxFor`? It's not yet released on NPM. The experimental subpackage for `rxFor` is not available yet.
